# Generated by Django 3.0 on 2021-07-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0054_auto_20210629_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='semester',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='ca',
            name='year_of_study',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ca',
            name='academic_year',
            field=models.CharField(default='2020/2021', max_length=9),
        ),
        migrations.AlterField(
            model_name='ca',
            name='ca',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='CourseWorkAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.IntegerField(default=1, null=True)),
                ('semester', models.IntegerField(default=1, null=True)),
                ('academic_year', models.CharField(default='2020/2021', max_length=9)),
                ('ca', models.IntegerField(default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Student')),
            ],
        ),
    ]
