# Generated by Django 3.0 on 2021-07-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0055_auto_20210702_2158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseworkassessment',
            unique_together={('student', 'course', 'year_of_study', 'semester', 'academic_year')},
        ),
    ]
